/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FileData
 */
export interface FileData {
    /**
     * Base64 representation of the file
     * @type {string}
     * @memberof FileData
     */
    'data': string;
    /**
     * 
     * @type {string}
     * @memberof FileData
     */
    'name': string;
}

