/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProgressResponse
 */
export interface ProgressResponse {
    /**
     * The progress with a range of 0 to 1
     * @type {number}
     * @memberof ProgressResponse
     */
    'progress': number;
    /**
     * 
     * @type {number}
     * @memberof ProgressResponse
     */
    'eta_relative': number;
    /**
     * The current state snapshot
     * @type {object}
     * @memberof ProgressResponse
     */
    'state': object;
    /**
     * The current image in base64 format. opts.show_progress_every_n_steps is required for this to work.
     * @type {string}
     * @memberof ProgressResponse
     */
    'current_image'?: string;
}

