/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SamplerItem
 */
export interface SamplerItem {
    /**
     * 
     * @type {string}
     * @memberof SamplerItem
     */
    'name': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SamplerItem
     */
    'aliases': Array<string>;
    /**
     * 
     * @type {{ [key: string]: string | undefined; }}
     * @memberof SamplerItem
     */
    'options': { [key: string]: string | undefined; };
}

