/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SDModelItem
 */
export interface SDModelItem {
    /**
     * 
     * @type {string}
     * @memberof SDModelItem
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof SDModelItem
     */
    'model_name': string;
    /**
     * 
     * @type {string}
     * @memberof SDModelItem
     */
    'hash': string;
    /**
     * 
     * @type {string}
     * @memberof SDModelItem
     */
    'filename': string;
    /**
     * 
     * @type {string}
     * @memberof SDModelItem
     */
    'config': string;
}

