/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpscalerItem
 */
export interface UpscalerItem {
    /**
     * 
     * @type {string}
     * @memberof UpscalerItem
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UpscalerItem
     */
    'model_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpscalerItem
     */
    'model_path'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpscalerItem
     */
    'model_url'?: string;
}

